### ISSUE TITLE
Preview app sinks open document with Editor

### ISSUE THREAD

**Issue by akaDuality** [VODGroup/VoiceOverDesigner#11]
- [x] Read ['Designing for Documents for iCloud'](https://developer.apple.com/library/archive/documentation/General/Conceptual/iCloudDesignGuide/Chapters/DesigningForDocumentsIniCloud.html#//apple_ref/doc/uid/TP40012094-CH2-SW1)
- [x] [Save document to iCloud](https://developer.apple.com/documentation/foundation/icloud)
- [x] UIDocument should use fileCoordinator to update synced controls
## Handoff
- [x] #217

# Tasks
- [x] #172
