### ISSUE TITLE
iPad version

### ISSUE THREAD

**Issue by akaDuality** [VODGroup/VoiceOverDesigner#136]
It will be cool to have possibility to draw on an iPad. Just imagine: we can draw, setup and launch VoiceOver just on single device.

> Looks reasonable to use SwiftUI, but we wrote enough UI-related logic for AppKit already.

## Stage 1
We already can draw for iOS, wouldn't change this code yet.
- [ ] Add ability to draw an elements like the one on AppKit, but for UIKit. Reuse `CanvasPresenter`, create separate module for them. E.g.: `CanvasAppKit`, `CanvasUIKit`, `Canvas`
- [ ] Create ViewController for Settings and write it on SwiftUI if possible. 
- [ ] Reuse SwiftUI-Settings for macOS app if possible

## Stage 2
- [ ] Rewrite TextUI module to SwiftUI, use it for both app
- [ ] Rewrite Canvas if needed to SwiftUI

**Comment by drucelweisse** [comment]
I think, we need additional stage where iPadOS target is set up

**Comment by akaDuality** [comment]
Good point. Probably, we can toggle iPad features in some way. For e.g. you can draw or select rects only by Apple Pencil :D
