### ISSUE TITLE
Add samples to projects window

### ISSUE THREAD

**Issue by akaDuality** [VODGroup/VoiceOverDesigner#187]
The most important part of the app is to teach people. We can provide our samples for learning purpose.

It can be achieved by [on-demand resources.](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/On_Demand_Resources_Guide/)

## Tasks
- [x] Load single document
- [x] Create sample json and put it to samples folder at Samples repository
- [x] Add cache
- [x] Output samples document by loading preview only
- [x] Add tab for samples
- [x] Calc available languages on the fly
- [x] Apply language selection
- [x] Select language according to current locale
- [x] Divide sections by projects
- [x] Reset language submenu after loading
- [x] Save document when close the one
- [x] Save document to language folder
- [ ] Strange behaviour after saving
- [ ] Show samples if there in no user's documents
- [x] Remember selected language
- [ ] Remember last opened tab
- [ ] Remove samples that is not presented in structure.json?

## Image loading
- [x] Add icon to show that loading is needed
- [x] Prefetch and cache samples structure
- [x] Add loading state for previews and for document
- [x] Update images after loading
- [x] Save preview to `.heic`
- [x] Support old-versioned `.png` preview
- [x] Check why cloud document's won't read preview
- [x] Image disappears when black-white appearance changes
- [x] Update samples to new structure
- [ ] Load documents' previews in parallel
- [ ] #224

## UI tests
- [ ] Structure loading
- [ ] Language can be changed, but remember last selection between tab's switches and restarting

## Preview
- [ ] #225

## Infrastructure
- [x] Add file version property to make graceful updates
- [x] Add file size to track downloading progress
- [x] Create a tool that create json with samples structures
- [ ] Add this tool to GitHub CI
- [ ] Add more samples for Pizza, remove samples for Drinkit (we should make more samples for different languages)
- [ ] Reload document if version changed. Add version to regular document?

**Comment by drucelweisse** [comment]
It seems to work only with iOS apps. Is there an intent to support that in release?

**Comment by akaDuality** [comment]
It looks like important part of first onboarding. 

We can put samples to some CDN (or just find the way how to download everything from github) and download it after first install

**Comment by drucelweisse** [comment]
It seems that the way to do this task is download documents from some CDN via URLSession. Unfortunately github doesn't serve files and treats it as folder(which is technically true). And then we can use NSDocumentController.duplicate function to create a copy https://developer.apple.com/documentation/appkit/nsdocumentcontroller/1514982-duplicatedocument

**Comment by akaDuality** [comment]
@drucelweisse we can host documents at Github pages :D
