### ISSUE TITLE
Create undo for element's settings

### ISSUE THREAD

**Issue by akaDuality** [VODGroup/VoiceOverDesigner#327]
Undo operation is broken. Previously the app observed changes in the array of elements, but after reworking the Artboard format setter for elements isn't called more.

## TODO
- [ ] Observe change in element, add support for undo.
- [ ] Add UI-tests for that
- [ ] Repeat for container and frame
